# -*- coding: utf-8 -*-
"""2_Análise_de_Licitações.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JVTKNGldGN8ZS8kHGr8GfqM2sZZ-VkoY
"""

import requests
import pandas as pd

url = "http://wstransparencia.pma.es.gov.br/api/Licitacao/"

response = requests.get(url)

data = response.json()

df = pd.DataFrame(data)
st.write(df)